data:
  path: "./data/sysevr_splited_len"
  train_domain:
    - "API_function_call"
  #    - "Arithmetic_expression"
  #    - "Pointer_usage"
  test_domain:
    - "Array_usage"
  source: "afc"
  target: "au"
  pretrain: "word2vec"
  train_loader: "${data.source}_train_loader_${model.support}.pkl"
  vocabulary: "${data.source}_vocabulary_${model.support}.pkl"
  weights: "${data.source}_${data.pretrain}_weights_${model.support}.pkl"
  dev_loader: "dev_loader_${data.target}_${model.support}.pkl"
  test_loader: "test_loader_${data.target}_${model.support}.pkl"
  window: 64
  min_count: 1
  min_freq: 1
  seed: 42

model:
  seed: 42
  support: 50
  query: 50
  log_interval: 10
  dev_interval: 50
  early_stop: 100
  class: 2
  encoder:
    type: "rnn_attn"
    rnn_type: "gru"
    embed_dim: 64
    hidden_dim: 64
    num_layers: 1
    dropout: 0.0
  iterations: 10
  relation_dim: 100
  lr: 0.0001
  log_path: "./log/${data.source}_${data.target}_${model.support}/sysevr_${model.encoder.type}_${model.encoder.rnn_type}"
  model_path: "${model.log_path}/ckpt.pth"
  episodes: 15000

loader:
  num_workers: 0
  pin_memory: false
