data:
  path: "./data/sysevr_splited"
  train_domain:
    - "API_function_call"
    # - "Arithmetic_expression"
    # - "Pointer_usage"
  test_domain:
    - "Array_usage"
  train_loader: "train_loader.pkl"
  dev_loader: "dev_loader.pkl"
  test_loader: "test_loader.pkl"
  vocabulary: "vocabulary.pkl"
  weights: "weights.pkl"
  window: 64
  min_count: 1
  min_freq: 1
  seed: 42

model:
  seed: 42
  support: 5
  query: 27
  log_interval: 10
  dev_interval: 50
  early_stop: 70
  class: 2
  embed_dim: 64
  hidden_dim: 128
  d_a: 64
  iterations: 3
  relation_dim: 100
  lr: 1e-4
  log_path: "./log/sysevr"
  model_path: "ckpt.pth"
  episodes: 10000

loader:
  num_workers: 0
  pin_memory: false
