data:
  path: "./data/sysevr_splited"
  train_domain:
    - "API_function_call"
    # - "Arithmetic_expression"
    # - "Pointer_usage"
  test_domain:
    - "Array_usage"
  train_loader: "train_loader.pkl"
  dev_loader: "dev_loader.pkl"
  test_loader: "test_loader.pkl"
  vocabulary: "vocabulary.pkl"
  weights: "weights.pkl"
  window: 64
  min_count: 1
  min_freq: 1
  seed: 42

model:
  type: "lstm"
  seed: 42
  support: 100
  query: 100
  log_interval: 10
  dev_interval: 200
  early_stop: 70
  class: 2
  embed_dim: 64
  hidden_dim: 64
  num_layers: 1
  iterations: 10
  relation_dim: 100
  lr: 1e-4
  log_path: "./log/sysevr_lstm"
  model_path: "./log/sysevr_lstm/ckpt.pth"
  episodes: 10000

loader:
  num_workers: 0
  pin_memory: false
