data:
  path: "./data/sysevr_splited_len"
  train_domain:
    - "API_function_call"
  #    - "Arithmetic_expression"
  #    - "Pointer_usage"
  test_domain:
    - "Array_usage"
  source: "afc"
  target: "au"
  pretrain: "fasttext"
  save_path: "${data.source}_${data.target}_${model.support}_${model.query}_${data.seed}"
  train_loader: "${data.save_path}/train_loader.pkl"
  vocabulary: "${data.save_path}/vocabulary.pkl"
  weights: "${data.save_path}/${data.pretrain}_weights.pkl"
  dev_loader: "${data.save_path}/dev_loader.pkl"
  test_loader: "${data.save_path}/test_loader.pkl"
  window: 64
  min_count: 1
  min_freq: 1
  seed: 42

model:
  seed: 42
  support: 200
  query: 100
  log_interval: 10
  dev_interval: 100
  early_stop: 100
  class: 2
  encoder:
    type: "rnn"
    rnn_type: "lstm"
    embed_dim: 64
    hidden_dim: 64
    num_layers: 1
    dropout: 0.0
  iterations: 10
  relation_dim: 100
  lr: 0.0001
  log_path: "./log/${data.save_path}/sysevr_${model.encoder.type}_${model.encoder.rnn_type}/${data.pretrain}"
  model_path: "${model.log_path}/ckpt.pth"
  episodes: 15000

loader:
  num_workers: 0
  pin_memory: false
